# .github/jules.yaml
# Version: 2.4.0 - Environment Stability & Meraki-Focus

instructions: |
  CRITICAL: All Pull Requests MUST target the 'beta' branch.

  ENVIRONMENT MANAGEMENT:
  - Before any 'git rebase' or 'git merge', you MUST run 'rm -rf .venv/ archive/agent-artifacts/ .pytest_cache/ .ruff_cache/ __pycache__/' to ensure a lean filesystem and prevent 'too many files affected' errors.
  - After git operations, re-initialize your environment by running 'pip install -r requirements.txt'.

  VALIDATION & CI:
  - Before pushing code, you MUST run 'pip install -r requirements.txt', 'ruff check .', and 'pytest' locally in your VM.
  - Always check '.github/workflows/' for the latest CI definitions (e.g., 'validate-code.yml') before diagnosing failures.
  - If you encounter a merge conflict in 'requirements_dev.txt', prioritize maintaining existing dev-tools while resolving version pins.

  PROJECT GOVERNANCE:
  - Follow Home Assistant Core integration standards (PEP8, async/await).
  - IGNORE all errors or logs not directly related to the 'meraki_ha' integration or its specific dependencies.

project_context:
  primary_branch: main
  development_branch: beta
  coding_standards: 'Home Assistant Core (async/await, strict typing)'
  ignored_errors: 'All errors not related to the meraki_ha integration.'
