# Jules AI Agent Configuration
# https://jules.google/docs/api/reference/

project_context:
  # Branch configuration
  primary_branch: main
  development_branch: beta

  # Project description
  description: |
    Cisco Meraki integration for Home Assistant. Allows users to monitor and manage
    Meraki network infrastructure (access points, switches, cameras, security appliances,
    and environmental sensors) directly from Home Assistant.

  # Technology stack
  technologies:
    - Python 3.13
    - Home Assistant Core
    - meraki SDK
    - aiohttp
    - React
    - TypeScript
    - Vite

  # Coding standards
  coding_standards: |
    - Follow Home Assistant Core integration standards
    - PEP 8 and Ruff linting rules
    - Use async/await for all I/O operations
    - Type hints required for all function signatures
    - NumPy-style docstrings
    - Use uv for package management (never requirements.txt)
    - All configurations in pyproject.toml
    - Conventional Commits format for commit messages

  # Important project patterns
  patterns: |
    - Optimistic UI with Cooldown: For entities that modify Meraki config, update state
      immediately, make fire-and-forget API call, register pending update with coordinator
      (default 150 seconds cooldown)
    - Use CoordinatorEntity for data updates
    - API client uses snake_case methods
    - Constants defined in const.py
    - Validation using voluptuous schemas

  # Files to read for context
  context_files:
    - AGENTS.md
    - DEVELOPMENT.md
    - pyproject.toml

  # Key directories
  key_directories:
    integration: custom_components/meraki_ha/
    tests: tests/
    frontend: custom_components/meraki_ha/www/
    workflows: .github/workflows/

  # Ignored errors - focus only on meraki_ha integration
  ignored_errors: |
    Ignore all errors not related to the meraki_ha integration.
    Ignore pip-audit vulnerabilities that are already acknowledged in CI.

  # Quality requirements
  quality_requirements: |
    - 95%+ test coverage
    - All tests must pass
    - No ruff or mypy errors
    - No bandit security warnings
    - Frontend must build without errors

  # CRITICAL: Issue documentation requirements
  issue_documentation: |
    ## You MUST Document Your Work on the Issue

    Future AI agents will read issue comments to understand what was done.
    You MUST update the issue at key points using `gh issue comment`.

    ### When to Comment on the Issue
    1. When you START working - what you plan to do
    2. After ANALYZING the problem - what you found
    3. After making CHANGES - what you changed and WHY
    4. If you encounter PROBLEMS - what went wrong
    5. When you CREATE a PR - link to PR and summarize

    ### How to Comment
    ```bash
    gh issue comment <ISSUE_NUMBER> --body "## 🤖 Jules Update

    ### What I Did
    <Describe the changes>

    ### Why I Did It
    <Explain your reasoning>

    ### Files Changed
    <List key files>

    ### Next Steps
    <What happens next>

    ---
    *Jules AI Agent*"
    ```

    ### PR/Branch Linking
    - PR body MUST contain: `Closes #<issue_number>`
    - Branch name should include issue number
    - Use `gh pr edit` to add labels linking to issue

    ### For Future Agents
    Your comments help the next agent (Jules or Cursor) understand:
    - What approaches were tried
    - What worked and what didn't
    - Why certain decisions were made
    - What's left to do

  # CRITICAL: Handoff behavior when stuck
  handoff_when_stuck: |
    ## ⚠️ NEVER WAIT FOR A HUMAN - ALWAYS HAND OFF TO CURSOR ⚠️

    You are NEVER allowed to stop and wait for human intervention.
    If you encounter ANY difficulty, hand off to Cursor IMMEDIATELY.

    ### When to Hand Off (after 1-2 attempts):
    - CI failures you cannot resolve
    - Errors you don't understand
    - Unclear requirements
    - Complex architectural decisions
    - Tests failing for unknown reasons
    - Going in circles on the same issue
    - ANY situation where you're stuck

    ### HOW TO HAND OFF:
    1. Create/update PR with current progress (even if incomplete/broken)
    2. Run: `gh pr edit <PR#> --add-label "jules-needs-help"`
    3. Comment on PR with this format:

    ## 🆘 Jules Needs Cursor Help

    **Where I Got Stuck:**
    <The specific problem>

    **What I've Tried:**
    <Your attempts>

    **Current Progress:**
    <What's done vs remaining>

    **Files Changed:**
    <Key files modified>

    **Suggested Next Steps:**
    <What Cursor should try>

    ---
    *Handing off to Cursor*

    ### CRITICAL RULES:
    - NEVER stop without creating a PR
    - NEVER wait for a human
    - Cursor will take over IMMEDIATELY
    - This is an AUTOMATED workflow - humans only review at the end
