# .github/jules.yaml
instructions: |
  CRITICAL: All Pull Requests MUST target the beta branch.
  Before pushing any code, you MUST run pip install -r requirements.txt, ruff check ., and pytest locally in your VM.
  Always check .github/workflows/ for the latest CI definitions (e.g., validate-code.yml) before diagnosing failures.
project_context:
  primary_branch: main
  development_branch: beta
  coding_standards: 'Follow Home Assistant Core integration standards (PEP8, async/await).'
  ignored_errors: 'Ignore all errors not related to the meraki_ha integration.'
