# .github/jules.yaml
instructions: |
  ALL Pull Requests must target the beta branch unless explicitly told otherwise.
  You must run `ruff check .` and `pytest` locally in your VM. If they fail, fix the code before pushing.
project_context:
  primary_branch: main
  development_branch: beta
  coding_standards: 'Follow Home Assistant Core integration standards (PEP8, async/await).'
  ignored_errors: 'Ignore all errors not related to the meraki_ha integration.'
