# Jules AI Agent Configuration
# https://jules.google/docs/api/reference/

project_context:
  # Branch configuration
  primary_branch: main
  development_branch: beta

  # Project description
  description: |
    Cisco Meraki integration for Home Assistant. Allows users to monitor and manage
    Meraki network infrastructure (access points, switches, cameras, security appliances,
    and environmental sensors) directly from Home Assistant.

  # Technology stack
  technologies:
    - Python 3.13
    - Home Assistant Core
    - meraki SDK
    - aiohttp
    - React
    - TypeScript
    - Vite

  # Coding standards
  coding_standards: |
    - Follow Home Assistant Core integration standards
    - PEP 8 and Ruff linting rules
    - Use async/await for all I/O operations
    - Type hints required for all function signatures
    - NumPy-style docstrings
    - Use uv for package management (never requirements.txt)
    - All configurations in pyproject.toml
    - Conventional Commits format for commit messages

  # Important project patterns
  patterns: |
    - Optimistic UI with Cooldown: For entities that modify Meraki config, update state
      immediately, make fire-and-forget API call, register pending update with coordinator
      (default 150 seconds cooldown)
    - Use CoordinatorEntity for data updates
    - API client uses snake_case methods
    - Constants defined in const.py
    - Validation using voluptuous schemas

  # Files to read for context
  context_files:
    - AGENTS.md
    - DEVELOPMENT.md
    - pyproject.toml

  # Key directories
  key_directories:
    integration: custom_components/meraki_ha/
    tests: tests/
    frontend: custom_components/meraki_ha/www/
    workflows: .github/workflows/

  # Ignored errors - focus only on meraki_ha integration
  ignored_errors: |
    Ignore all errors not related to the meraki_ha integration.
    Ignore pip-audit vulnerabilities that are already acknowledged in CI.

  # Quality requirements
  quality_requirements: |
    - 95%+ test coverage
    - All tests must pass
    - No ruff or mypy errors
    - No bandit security warnings
    - Frontend must build without errors

  # CRITICAL: Issue documentation requirements
  issue_documentation: |
    ## You MUST Document Your Work on the Issue

    Future AI agents will read issue comments to understand what was done.
    You MUST update the issue at key points using `gh issue comment`.

    ### When to Comment on the Issue
    1. When you START working - what you plan to do
    2. After ANALYZING the problem - what you found
    3. After making CHANGES - what you changed and WHY
    4. If you encounter PROBLEMS - what went wrong
    5. When you CREATE a PR - link to PR and summarize

    ### How to Comment
    ```bash
    gh issue comment <ISSUE_NUMBER> --body "## 🤖 Jules Update

    ### What I Did
    <Describe the changes>

    ### Why I Did It
    <Explain your reasoning>

    ### Files Changed
    <List key files>

    ### Next Steps
    <What happens next>

    ---
    *Jules AI Agent*"
    ```

    ### PR/Branch Linking
    - PR body MUST contain: `Closes #<issue_number>`
    - Branch name should include issue number
    - Use `gh pr edit` to add labels linking to issue

    ### For Future Agents
    Your comments help the next agent (Jules or Cursor) understand:
    - What approaches were tried
    - What worked and what didn't
    - Why certain decisions were made
    - What's left to do

  # CRITICAL: Handoff behavior when stuck
  handoff_when_stuck: |
    ## ⚠️ NEVER LOOP ENDLESSLY - HAND OFF TO CURSOR ⚠️

    You are NEVER allowed to keep trying the same fix repeatedly.
    If ./run_checks.sh fails with the SAME error after 2 attempts, STOP.

    ### STOP IMMEDIATELY when:
    - The SAME test/error fails twice after your fixes
    - You're running ./run_checks.sh more than 3 times
    - You see "This step is already complete" but checks still fail
    - You've tried 2 different approaches and both failed
    - Going in circles on the same issue

    ### This is NOT acceptable:
    - Running ./run_checks.sh 5+ times hoping for success
    - Saying "I fixed it" but not verifying with checks
    - Marking steps complete when they're not actually working

    ### HOW TO HAND OFF:
    1. Commit your current progress (even if broken)
    2. Create/update PR with current progress
    3. UPDATE THE ISSUE (not just PR) with handoff context:

    ```bash
    gh issue comment <ISSUE#> --body "## 🆘 Jules Handoff to Cursor

    ### ✅ What I Completed
    <list files changed and what you did>

    ### ❌ What I'm Stuck On
    <the exact error message from ./run_checks.sh>

    ### 🔧 What I Tried
    <your fix attempts that didn't work>

    ### 📝 Suggested Next Steps
    <what Cursor should try differently>

    ---
    *Handing off to Cursor*"
    ```

    4. Run: `gh pr edit <PR#> --add-label "jules-needs-help"`
    5. EXIT immediately

    ### CRITICAL RULES:
    - ALWAYS update the issue BEFORE adding the label
    - Cursor reads issue comments to understand context
    - NEVER stop without updating the issue
    - NEVER wait for a human
    - Cursor will take over IMMEDIATELY
