skips:
  - 'B101' # assert_used
  - 'B104' # hardcoded_bind_all_interfaces
  - 'B105' # hardcoded_password_string
  - 'B106' # hardcoded_password_funcarg
  - 'B107' # hardcoded_password_default
  - 'B110' # try_except_pass
  - 'B112' # try_except_continue
  - 'B311' # aandr_random
  - 'B404' # import_subprocess
  - 'B603' # subprocess_without_shell_equals_true
  - 'B607' # start_process_with_partial_path

exclude_dirs:
  - 'tests'
  - 'node_modules'
  - 'custom_components/meraki_ha/core/utils'
