name: 🤖 Ask Jules (AI Agent)
description: Create a structured task for the Jules coding agent.
title: '[Jules]: '
labels: ['jules-issue', 'status: todo', 'type: feature']
assignees: ['jules']

body:
  - type: markdown
    attributes:
      value: |
        ### 🤖 AI Agent Instructions
        When this issue is created, Jules will automatically begin analyzing the requirements based on `AGENTS.md`, `DEVELOPMENT.md`, and the `beta` branch.
  - type: input
    id: milestone
    attributes:
      label: Milestone
      value: 'v2.3.0 (2026.1 Infrastructure Update)'
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: Task Requirements
      description: Describe exactly what you want Jules to build or refactor.
      placeholder: 'e.g., Implement Requirement [E-1] from the Roadmap...'
    validations:
      required: true
  - type: textarea
    id: constraints
    attributes:
      label: Specific Constraints
      description: List any technical constraints (e.g., specific files to ignore).
      value: 'Ignore all errors not related to the meraki_ha integration. Follow Home Assistant Sentence Case standards.'
  - type: checkboxes
    id: target
    attributes:
      label: Target Branch
      options:
        - label: This work must target the 'beta' branch.
          required: true
