# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Meraki integration for Home Assistant
version: "0.1.15"
slug: meraki-homeassistant
description: Meraki integration for Home Assistant
url: "https://github.com/brewmarsh/meraki-home-assistant"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "To obtain your API key, navigate to the Meraki dashboard, go to Organization -> API & Webhooks -> API keys and access and generate an API key."
  api_key: ""
  organization_id: ""
  polling_interval: "60"
schema:
  message: "str"
  api_key: "str"
  organization_id: "str"
  polling_interval: "list(15|30|45|60)"
#description: "To obtain your API key, navigate to the Meraki dashboard, go to Organization -> API & Webhooks -> API keys and access and generate an API key."
#image: "meraki-homeassistant-logo.png"
