#!/bin/bash
# Auto-generated script to delete orphaned Meraki entities
# Review carefully before running!

if [ -z "$HA_TOKEN" ]; then
  echo "Error: Set HA_TOKEN environment variable first"
  exit 1
fi

curl -X DELETE "http://192.168.14.50/api/config/entity_registry/switch.vlan_homenet_dhcp" -H "Authorization: Bearer $HA_TOKEN"
echo "Deleted: switch.vlan_homenet_dhcp"
curl -X DELETE "http://192.168.14.50/api/config/entity_registry/switch.vlan_users_dhcp_2" -H "Authorization: Bearer $HA_TOKEN"
echo "Deleted: switch.vlan_users_dhcp_2"
curl -X DELETE "http://192.168.14.50/api/config/entity_registry/switch.vlan_sonos_dhcp" -H "Authorization: Bearer $HA_TOKEN"
echo "Deleted: switch.vlan_sonos_dhcp"
curl -X DELETE "http://192.168.14.50/api/config/entity_registry/switch.vlan_iot_dhcp" -H "Authorization: Bearer $HA_TOKEN"
echo "Deleted: switch.vlan_iot_dhcp"
curl -X DELETE "http://192.168.14.50/api/config/entity_registry/switch.vlan_kids_dhcp" -H "Authorization: Bearer $HA_TOKEN"
echo "Deleted: switch.vlan_kids_dhcp"
curl -X DELETE "http://192.168.14.50/api/config/entity_registry/switch.vlan_voip_dhcp" -H "Authorization: Bearer $HA_TOKEN"
echo "Deleted: switch.vlan_voip_dhcp"
curl -X DELETE "http://192.168.14.50/api/config/entity_registry/switch.vlan_lab_net_dhcp" -H "Authorization: Bearer $HA_TOKEN"
echo "Deleted: switch.vlan_lab_net_dhcp"
curl -X DELETE "http://192.168.14.50/api/config/entity_registry/switch.vlan_asrptp_dhcp" -H "Authorization: Bearer $HA_TOKEN"
echo "Deleted: switch.vlan_asrptp_dhcp"
curl -X DELETE "http://192.168.14.50/api/config/entity_registry/switch.vlan_internet_route_dhcp" -H "Authorization: Bearer $HA_TOKEN"
echo "Deleted: switch.vlan_internet_route_dhcp"
curl -X DELETE "http://192.168.14.50/api/config/entity_registry/switch.vlan_home_remote_dhcp" -H "Authorization: Bearer $HA_TOKEN"
echo "Deleted: switch.vlan_home_remote_dhcp"
curl -X DELETE "http://192.168.14.50/api/config/entity_registry/switch.vlan_iot_remote_dhcp" -H "Authorization: Bearer $HA_TOKEN"
echo "Deleted: switch.vlan_iot_remote_dhcp"
curl -X DELETE "http://192.168.14.50/api/config/entity_registry/switch.vlan_home_admin_dhcp" -H "Authorization: Bearer $HA_TOKEN"
echo "Deleted: switch.vlan_home_admin_dhcp"
curl -X DELETE "http://192.168.14.50/api/config/entity_registry/switch.vlan_ap_mgmt_dhcp_3" -H "Authorization: Bearer $HA_TOKEN"
echo "Deleted: switch.vlan_ap_mgmt_dhcp_3"
curl -X DELETE "http://192.168.14.50/api/config/entity_registry/sensor.camera_camera_office_status" -H "Authorization: Bearer $HA_TOKEN"
echo "Deleted: sensor.camera_camera_office_status"
curl -X DELETE "http://192.168.14.50/api/config/entity_registry/sensor.camera_camera_front_door_status" -H "Authorization: Bearer $HA_TOKEN"
echo "Deleted: sensor.camera_camera_front_door_status"
curl -X DELETE "http://192.168.14.50/api/config/entity_registry/sensor.camera_camera_meraki_mv2_q2nv_72up_y6ab_status" -H "Authorization: Bearer $HA_TOKEN"
echo "Deleted: sensor.camera_camera_meraki_mv2_q2nv_72up_y6ab_status"
curl -X DELETE "http://192.168.14.50/api/config/entity_registry/sensor.camera_camera_garadge_status" -H "Authorization: Bearer $HA_TOKEN"
echo "Deleted: sensor.camera_camera_garadge_status"
curl -X DELETE "http://192.168.14.50/api/config/entity_registry/sensor.camera_camera_meraki_mv2_q2nv_cygt_z6yd_status" -H "Authorization: Bearer $HA_TOKEN"
echo "Deleted: sensor.camera_camera_meraki_mv2_q2nv_cygt_z6yd_status"
curl -X DELETE "http://192.168.14.50/api/config/entity_registry/sensor.camera_camera_utility_room_status" -H "Authorization: Bearer $HA_TOKEN"
echo "Deleted: sensor.camera_camera_utility_room_status"
curl -X DELETE "http://192.168.14.50/api/config/entity_registry/sensor.cellulargateway_cellulargateway_home_mint_connected_clients" -H "Authorization: Bearer $HA_TOKEN"
echo "Deleted: sensor.cellulargateway_cellulargateway_home_mint_connected_clients"
curl -X DELETE "http://192.168.14.50/api/config/entity_registry/sensor.camera_camera_meraki_mv53x_q4eg_84av_sqdy_status" -H "Authorization: Bearer $HA_TOKEN"
echo "Deleted: sensor.camera_camera_meraki_mv53x_q4eg_84av_sqdy_status"
curl -X DELETE "http://192.168.14.50/api/config/entity_registry/sensor.camera_camera_basement_1_status" -H "Authorization: Bearer $HA_TOKEN"
echo "Deleted: sensor.camera_camera_basement_1_status"
curl -X DELETE "http://192.168.14.50/api/config/entity_registry/sensor.camera_camera_basement_2_status" -H "Authorization: Bearer $HA_TOKEN"
echo "Deleted: sensor.camera_camera_basement_2_status"
curl -X DELETE "http://192.168.14.50/api/config/entity_registry/sensor.camera_camera_basement_3_status" -H "Authorization: Bearer $HA_TOKEN"
echo "Deleted: sensor.camera_camera_basement_3_status"
curl -X DELETE "http://192.168.14.50/api/config/entity_registry/sensor.camera_camera_driveway_status" -H "Authorization: Bearer $HA_TOKEN"
echo "Deleted: sensor.camera_camera_driveway_status"
curl -X DELETE "http://192.168.14.50/api/config/entity_registry/sensor.camera_camera_backyard_status" -H "Authorization: Bearer $HA_TOKEN"
echo "Deleted: sensor.camera_camera_backyard_status"
curl -X DELETE "http://192.168.14.50/api/config/entity_registry/sensor.camera_camera_front_yard_status" -H "Authorization: Bearer $HA_TOKEN"
echo "Deleted: sensor.camera_camera_front_yard_status"
curl -X DELETE "http://192.168.14.50/api/config/entity_registry/sensor.camera_camera_meraki_mv73m_q4ej_twbr_magf_status" -H "Authorization: Bearer $HA_TOKEN"
echo "Deleted: sensor.camera_camera_meraki_mv73m_q4ej_twbr_magf_status"
curl -X DELETE "http://192.168.14.50/api/config/entity_registry/sensor.camera_camera_patio_status" -H "Authorization: Bearer $HA_TOKEN"
echo "Deleted: sensor.camera_camera_patio_status"
