# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

_file_map = {

    "extract_intent.baml": "class Intent {\n  category string\n  confidence float\n}\n\nfunction ExtractIntent(input: string) -> Intent {\n  client \"openai/gpt-4o\"\n  prompt #\"\n    Extract the intent from the following input:\n    {{ input }}\n\n    {{ ctx.output_format }}\n  \"#\n}\n",
    "generators.baml": "generator Default {\n  output_type \"python/pydantic\"\n  output_dir \"../\"\n  version \"0.219.0\"\n}\n",
}

def get_baml_files():
    return _file_map