# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (2)
# #########################################################################

class Intent(BaseModel):
    category: typing.Optional[str] = None
    confidence: typing.Optional[float] = None

class MerakiIntentResponse(BaseModel):
    intent: typing.Optional[types.MerakiIntent] = None
    target_device: typing.Optional[str] = None
    guest_name: typing.Optional[str] = None
    duration_minutes: typing.Optional[int] = None
    network_name: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
