# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Intent": types.Intent,
    "stream_types.Intent": stream_types.Intent,

    "types.MerakiIntentResponse": types.MerakiIntentResponse,
    "stream_types.MerakiIntentResponse": stream_types.MerakiIntentResponse,


    "types.MerakiIntent": types.MerakiIntent,

}