# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
from baml_py import type_builder
from baml_py import baml_py
# These are exports, not used here, hence the linter is disabled
from baml_py.baml_py import FieldType, EnumValueBuilder, EnumBuilder, ClassBuilder # noqa: F401 # pylint: disable=unused-import
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME

class TypeBuilder(type_builder.TypeBuilder):
    def __init__(self):
        super().__init__(classes=set(
          ["Intent","MerakiIntentResponse",]
        ), enums=set(
          ["MerakiIntent",]
        ), runtime=DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME)

    # #########################################################################
    # Generated enums 1
    # #########################################################################

    @property
    def MerakiIntent(self) -> "MerakiIntentViewer":
        return MerakiIntentViewer(self)


    # #########################################################################
    # Generated classes 2
    # #########################################################################

    @property
    def Intent(self) -> "IntentViewer":
        return IntentViewer(self)

    @property
    def MerakiIntentResponse(self) -> "MerakiIntentResponseViewer":
        return MerakiIntentResponseViewer(self)



# #########################################################################
# Generated enums 1
# #########################################################################

class MerakiIntentAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("MerakiIntent")
        self._values: typing.Set[str] = set([  "RebootDevice",  "GenerateGuestAccess",  "CycleSwitchPort",  "GetNetworkStatus",  "Unknown",  ])
        self._vals = MerakiIntentValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "MerakiIntentValues":
        return self._vals


class MerakiIntentViewer(MerakiIntentAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)


    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]


class MerakiIntentValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821



    @property
    def RebootDevice(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("RebootDevice"))

    @property
    def GenerateGuestAccess(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("GenerateGuestAccess"))

    @property
    def CycleSwitchPort(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("CycleSwitchPort"))

    @property
    def GetNetworkStatus(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("GetNetworkStatus"))

    @property
    def Unknown(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Unknown"))





# #########################################################################
# Generated classes 2
# #########################################################################

class IntentAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Intent")
        self._properties: typing.Set[str] = set([  "category",  "confidence",  ])
        self._props = IntentProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "IntentProperties":
        return self._props


class IntentViewer(IntentAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)


    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class IntentProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821



    @property
    def category(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("category"))

    @property
    def confidence(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("confidence"))




class MerakiIntentResponseAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("MerakiIntentResponse")
        self._properties: typing.Set[str] = set([  "intent",  "target_device",  "guest_name",  "duration_minutes",  "network_name",  ])
        self._props = MerakiIntentResponseProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "MerakiIntentResponseProperties":
        return self._props


class MerakiIntentResponseViewer(MerakiIntentResponseAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)


    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class MerakiIntentResponseProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821



    @property
    def intent(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("intent"))

    @property
    def target_device(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("target_device"))

    @property
    def guest_name(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("guest_name"))

    @property
    def duration_minutes(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("duration_minutes"))

    @property
    def network_name(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("network_name"))
