---
name: Beta Python Linting

on:
  push:
    branches: ['beta']
  pull_request:
    branches: ['beta']

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to commit and push changes
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.9
        uses: actions/setup-python@v6
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 mypy pydocstyle black bandit
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
      - name: Check formatting with black
        run: black --check custom_components/meraki_ha/ tests/
      - name: Lint with flake8
        run: flake8 custom_components/meraki_ha/ tests/
      - name: Type check with mypy
        run: mypy custom_components/meraki_ha/ tests/
      - name: Docstring check with pydocstyle
        run: pydocstyle custom_components/meraki_ha/ tests/
      - name: Security scan with bandit
        run: bandit -r custom_components/meraki_ha/ -c .bandit.yaml
      - name: Run tests with coverage
        continue-on-error: true
        run: pytest --cov=custom_components.meraki_ha tests/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: brewmarsh/meraki-homeassistant