name: Generate Changelog

on:
  push:
    branches:
      - main # or your main branch

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed for git history

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Or your desired version

      - name: Install dependencies
        run: npm install

      - name: Generate Changelog
        run: npx conventional-changelog -p angular -i CHANGELOG.md -s

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update CHANGELOG.md'
