name: Increment Version on Merge

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'custom_components/meraki-ha/**'

jobs:
  increment_version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions: # added permissions section
      contents: write # grants write permission to the contents of the repo.
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install semver
        run: pip install semver

      - name: Determine Increment Type and Increment Version
        id: increment
        run: |
          python .github/workflows/increment_version.py minor
          if [[ "${{ github.event.pull_request.title }}" == *"[minor]"* ]]; then
            echo "increment_type=minor" >> $GITHUB_OUTPUT
          python .github/workflows/increment_version.py minor
          elif [[ "${{ github.event.pull_request.title }}" == *"[major]"* ]]; then
            echo "increment_type=major" >> $GITHUB_OUTPUT
            python .github/workflows/increment_version.py major
          else
            python .github/workflows/increment_version.py patch
            echo "increment_type=patch" >> $GITHUB_OUTPUT
          fi
      - name: Display manifest.json content
        run: cat custom_components/meraki-ha/manifest.json
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Incremented version ( ${{ steps.increment.outputs.increment_type }} )"
          file_pattern: custom_components/meraki-ha/manifest.json