name: Increment Version on Merge

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'custom_components/meraki-ha/**'

jobs:
  increment_version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install semver
        run: pip install semver

      - name: Determine Increment Type and Increment Version
        id: increment
        run: |
          if [[ "${{ github.event.pull_request.title }}" == *"[minor]"* ]]; then
            increment_type="minor"
          elif [[ "${{ github.event.pull_request.title }}" == *"[major]"* ]]; then
            increment_type="major"
          else
            increment_type="patch"
          fi
          python .github/workflows/increment_version.py "$increment_type"
          echo "increment_type=$increment_type" >> "$GITHUB_OUTPUT"

      - name: Display manifest.json content
        run: cat custom_components/meraki-ha/manifest.json

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Incremented version ( ${{ steps.increment.outputs.increment_type }} )'
          file_pattern: custom_components/meraki-ha/manifest.json
