---
name: Python Linting

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 mypy pydocstyle
          pip install -r requirements_dev.txt
      - name: Lint with flake8
        run: flake8 .
      - name: Type check with mypy
        run: mypy .
      - name: Docstring check with pydocstyle
        run: pydocstyle .
