name: Version and Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  version-and-release:
    runs-on: ubuntu-latest
    # Add condition to only run if the pull request was merged
    if: github.event.pull_request.merged == true
    permissions:
      contents: write # Needed to commit, push, and create releases
      pull-requests: read # Needed to read PR title
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch all history so conventional-changelog can determine version
          fetch-depth: 0 
          # Checkout the main branch explicitly, as the PR event might be on a different ref initially
          ref: main 

      - name: Set up Python and Node.js
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bump2version
          npm install

      - name: Increment Version
        id: increment
        run: |
          increment_type="patch" # Default increment type
          pr_title="${{ github.event.pull_request.title }}"

          if [[ "$pr_title" == *"[major]"* ]]; then
            increment_type="major"
          elif [[ "$pr_title" == *"[minor]"* ]]; then
            increment_type="minor"
          fi

          bump2version --allow-dirty $increment_type
          new_version=$(grep -oP '"version": "\K[^"]+' custom_components/meraki_ha/manifest.json)
          echo "new_version=$new_version" >> "$GITHUB_OUTPUT"

      - name: Update package.json version
        if: steps.increment.outputs.new_version != ''
        run: |
          echo "Synchronizing package.json version to: ${{ steps.increment.outputs.new_version }}"
          npm version ${{ steps.increment.outputs.new_version }} --no-git-tag-version --allow-same-version
          echo "--- package.json (after npm version) ---"
          cat package.json
          echo "--- end package.json (after npm version) ---"

      - name: Generate Changelog
        if: steps.increment.outputs.new_version != ''
        run: npx conventional-changelog -p angular -i CHANGELOG.md -s

      - name: Commit and push changes
        if: steps.increment.outputs.new_version != ''
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'chore(release): update version to ${{ steps.increment.outputs.new_version }} and CHANGELOG'
          file_pattern: 'custom_components/meraki_ha/manifest.json CHANGELOG.md package.json .bumpversion.cfg package-lock.json'
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          branch: main

      - name: Create Release
        if: steps.increment.outputs.new_version != ''
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'v${{ steps.increment.outputs.new_version }}'
          release_name: 'Release v${{ steps.increment.outputs.new_version }}'
          body_path: 'CHANGELOG.md'
          draft: false
          prerelease: false
