name: Version and Release

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  version-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to commit and push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Get full history for changelog

      - name: Set up Python and Node.js
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bump2version
          npm install

      - name: Increment Version
        id: increment
        run: |
          # Log .bumpversion.cfg content
          echo "--- .bumpversion.cfg ---"
          cat .bumpversion.cfg
          echo "--- end .bumpversion.cfg ---"

          # Log manifest.json content BEFORE bump2version
          echo "--- manifest.json (before) ---"
          cat custom_components/meraki_ha/manifest.json
          echo "--- end manifest.json (before) ---"

          # Get current version
          current_version=$(jq -r .version custom_components/meraki_ha/manifest.json)
          echo "Current Version: $current_version"

          increment_type="patch" # Default
          #  Determine increment type (using labels is recommended)
          if [[ "${{ github.event.commits[0].message }}" == *"[minor]"* ]]; then
            increment_type="minor"
          elif [[ "${{ github.event.commits[0].message }}" == *"[major]"* ]]; then
            increment_type="major"
          fi
          echo "Increment Type: $increment_type"

          # Bump version
          bump2version "$increment_type" custom_components/meraki_ha/manifest.json
          echo "increment_type=$increment_type" >> "$GITHUB_OUTPUT"

          # Log manifest.json content AFTER bump2version
          echo "--- manifest.json (after) ---"
          cat custom_components/meraki_ha/manifest.json
          echo "--- end manifest.json (after) ---"

          # Get new version and log
          new_version=$(jq -r .version custom_components/meraki_ha/manifest.json)
          echo "New Version: $new_version"

      - name: Generate Changelog
        run: npx conventional-changelog -p angular -i CHANGELOG.md -s

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update version and CHANGELOG'
          file_pattern: 'custom_components/meraki_ha/manifest.json CHANGELOG.md package.json' # Adjust as needed
          push_options: ' --force'
          token: ${{ github.token }}

      - name: Create Release
        uses: actions/create-release@v1 # Or a newer version
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          tag_name: 'v${{ steps.increment.outputs.new_version }}'
          release_name: 'v${{ steps.increment.outputs.new_version }}'
          body_path: 'CHANGELOG.md'
          draft: false
          prerelease: false
